apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: blog
    owner: user
  name: blog-app
spec:
  containers:
  - env:
    - name: env
      value: DEV
    image: testing-blog:latest
    name: blog_app
    ports:
    - containerPort: 8080
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
