version: "3.3"

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "blog_db"
    ports:
      - "5432:5432"
    volumes:
      - "postgres-db-volume:/var/lib/postgresql/data"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      retries: 5
    restart: always

  blog_app:
    build: .
    command: >
      sh -c "sleep 10 &&
             python manage.py makemigrations &&
             python manage.py migrate &&
             gunicorn -b 0.0.0.0:8000 blog_site.wsgi:application"
    ports:
      - "80:8000"
    depends_on:
      - postgres
    volumes:
      - "./blog_site:/blog_app"

volumes:
  postgres-db-volume:
    external: false
