version: "3.3"

secrets:
  postgres_user:
    external: true
  postgres_password:
    external: true
  postgres_db:
    external: true

services:
  postgres:
    image: postgres:13
    secrets:
      - postgres_user
      - postgres_password
      - postgres_db
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: postgres_db
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", postgres_user]
      interval: 5s
      retries: 5
    restart: always

  blog_app:
    build: .
    ports:
      - "8000:8000"

volumes:
  postgres-db-volume:
    external: false
