apiVersion: apps/v1 
kind: Deployment
metadata:
  name: blog-db
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: blog-db
  template:
    metadata:
      labels:
        pod: blog-db
        app: blog-db
    spec:
      containers:
        - name: blog-db
          image: postgres:12
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
              name: blog-db-secrets
            - configMapRef:
                name: blog-db-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: blog-db-pv-claim
