apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-app
  labels:
    app: blog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog-app
      pod: blog
  template:
    metadata:
      labels:
        app: blog-app
        pod: blog
    spec:
      containers:
        - name: blog-app
          image: registry.hub.docker.com/lambrosopos/blog:latest
          ports:
            - containerPort: 8000
          env:
            - name: DJANGO_SECRET_KEY
              value: testingdjango123
            - name: DB_USER
              value: postgres
            - name: DB_PORT
              value: '5432'
            - name: DB_HOST
              value: blog-db
            - name: DB_PASSWORD
              value: postgres
