apiVersion: v1
kind: Service
metadata:
  name: blog-np
  labels:
    app: blog-app
spec:
  type: NodePort
  ports:
  - name: "http-port"
    protocol: "TCP"
    port: 8000
    targetPort: 8000
    nodePort: 30082
  selector:
    app: blog-app
