apiVersion: v1
kind: Service
metadata:
  name: blog-lb
spec:
  type: LoadBalancer
  ports:
  - name: "http-port"
    protocol: "TCP"
    port: 8080
    targetPort: 8000
    nodePort: 30082
  selector:
    app: blog-app
