name: AUTO DEPLOY BLOG APP

env:
  DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
  DOCKER_HUB_USERNAME: lambrosopos
  REPOSITORY_NAME: testing-blog

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Install Docker
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker
        run: docker login --username=$DOCKER_HUB_USERNAME --password=$DOCKER_HUB_PASSWORD
      - name: Build Image
        run: docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7 -t $DOCKER_HUB_USERNAME/$REPOSITORY_NAME:$IMAGE_TAG .
      - name: Push Image
        run: docker push $DOCKER_HUB_USERNAME/$REPOSITORY_NAME:$IMAGE_TAG
